.github/ISSUE_TEMPLATE/bug-report--admin-tool.md
.github/ISSUE_TEMPLATE/bug_report.md

- templates for website and mobile will follow

Update issue templates for bugs in Admin Tool

---

.github/workflows/codeql-analysis.yml
admin/package.json

https://github.com/socialincome-san/public/security/dependabot/2

fix nth-check@^2.0.1 security alert

---

.github/ISSUE_TEMPLATE/bug-report--admin-tool.md
.github/ISSUE_TEMPLATE/new-feature--admin-tool.md
.github/workflows/admin-pr.yml
.github/workflows/codeql-analysis.yml
.github/workflows/prettify-pr.yml
README.md
admin/.yarnrc

Also prettifies readme and so on independently from the admin

Extracted prettify from admin

---

.github/ISSUE_TEMPLATE/bug-report--admin-tool.md
.github/ISSUE_TEMPLATE/bug-report--mobile-app.md
.github/ISSUE_TEMPLATE/feature--admin-tool.md
.github/ISSUE_TEMPLATE/feature--mobile-app.md
.github/ISSUE_TEMPLATE/new-feature--admin-tool.md

Added the bug / feature templates for Mobile App

Update issue templates

---

README.md

Add some initial setup information for recipients app to global project Readme file.

Update readme after recipients app made public

---

.vscode/settings.json
CODEOWNERS
package-lock.json
ui/.storybook/preview.ts
ui/package.json
ui/public/ch.svg
ui/src/components/select/Select.stories.tsx
ui/src/components/select/Select.tsx
ui/tailwind.config.js
ui/tsconfig.json

[ui] Add select components

---

README.md

Minor grammar and sentence corrections to improve document readability

Proofread and make corrections to README

---

admin/src/App.tsx

[Admin] Specify logo for dark mode

---

recipients_app/lib/theme/theme.dart
recipients_app/pubspec.lock
recipients_app/pubspec.yaml

Add Unica77LL font to pubspec file and global app theme 
Solves #75

feat(recipients_app): Add Unica77LL font to global app theme

---

README.md

Added Contributor's Profile Pic List in the Readme.md using [contrib.rocks](https://contrib.rocks)

Update Readme with profiles of code contributors #55

---

.github/workflows/admin.yml
.github/workflows/codeql-analysis.yml
.github/workflows/functions.yml
.github/workflows/prettify-pr.yml
.github/workflows/ui.yml
Makefile
docker-compose.yaml
package-lock.json

- Starting from a plain repository, I still got some errors because the dependencies haven't been installed for the shared packages. Switched now to install everything. For me, `npm install` is quicker than `npm ci` since the later deletes the node_moduels every time.
- to make the checks required, we need to set unique names for the jobs, otherwise I can't select them in the UI

[shared] Minor setup changes & marking checks required

---

Dockerfile
admin/package.json
package-lock.json

Temporary fix for https://github.com/socialincome-san/public/issues/145

[Admin] Back to firecms 2.0.0-alpha.33

---

admin/package.json
package-lock.json

[admin] firecms 2.0.0-alpha.42

---

admin/src/index.css
shared/assets/fonts/02_Unica77LLSub-Character-Set.pdf
shared/assets/fonts/02_Unica77LLWeb-Character-Set.pdf
ui/src/so-ui.css

Adding path to smaller font package

---

functions/src/etl/importExchangeRates.ts
functions/src/index.ts
functions/tests/etl/importExchangeRates.test.ts
shared/src/types/admin/ExchangeRates.ts
shared/src/types/index.ts

- Migrating simple import logic from the old website
- Translated to typescript
- Added test

feature(functions): migrate exchange rates import

---

package-lock.json

Update lock-file correctly according to latest package.json

chore(deps): lock-file maintenance

---

website/components/ApplePay.tsx
website/pages/index.tsx

Mini example how to check if the browser / device supports Apple Pay

[website] Apple Pay Check

---

admin/src/collections/Contributions.ts
admin/src/collections/DonationCertificate.tsx
admin/src/collections/OperationalExpenses.ts
admin/src/collections/Payments.ts
admin/src/collections/Recipients.tsx
functions/src/etl/OrangeMoneyCSVCreator.ts

First step towards a more convenient admin usage. Keeping the most recent records at the top.

[Admin] Sort collections

---

ui/src/components/text-field/TextField.stories.tsx
ui/src/components/text-field/TextField.tsx

Add the text field component to the UI library.
See https://socialincome-san.github.io/public/pr-preview/pr-268/?path=/docs/components-text-field-textfield--standard

UI: Add text Field Component

---

.github/workflows/admin-update-snapshots.yml

Same script as for the other modules to update the baseline of the playwright test using a github comment.

feature[admin] add playwright test: update script

---

.github/workflows/prettify-pr.yml

See https://github.com/creyD/prettier_action/pull/112

Fix prettier

---

functions/src/donation_certificates/DonationCertificateHandler.ts

Addressing some of the comments in https://github.com/socialincome-san/public/pull/289

[bug] DonationCertificateHandler: year bug and mini improvements

---

functions/src/donation_certificates/DonationCertificateHandler.ts
shared/locales/fr/donation-certificate.json

closes https://github.com/socialincome-san/public/issues/300
@ssandino could also be used in other keys (everywhere where I added `{ context: genderContext }`) if you want to reformulate more.

[feature] Adding gender specific translations for donation certificate

---

functions/src/admin/SurveyManager.ts

The task failed with `Memory limit of 256 MiB exceeded with 256 MiB used. Consider increasing the memory limit, see https://cloud.google.com/functions/docs/configuring/memory`
If that doesn't work, I will change the code to be streaming rather of loading all recipients into memory.

Increase memory for survey creation task

---

admin/src/views/Scripts.tsx
functions/src/etl/ExchangeRateImporter.ts
functions/src/index.ts

ExchangeRateImporter

---

README.md
recipients_app/android/build.gradle
recipients_app/lib/core/cubits/payment/payments_cubit.dart
recipients_app/lib/data/models/payment/social_income_payment.dart
recipients_app/lib/data/models/payment/social_income_payment.g.dart
recipients_app/lib/data/models/recipient.dart
recipients_app/lib/data/models/recipient.g.dart
recipients_app/lib/data/repositories/payment_repository.dart
recipients_app/lib/data/repositories/user_repository.dart
recipients_app/lib/view/pages/payments_page.dart
recipients_app/lib/view/widgets/income/balance_card/balance_card_grid.dart

feat(recipient_app): Updated by payment field

---

shared/locales/en/website-home.json
ui/src/components/typography/typography.stories.tsx
website/src/app/[lang]/[country]/(website)/(home)/section-5.tsx

complete section-5

---

recipients_app/android/app/src/dev/google-services.json
recipients_app/ios/GoogleServicesConfig/GoogleService-Info-Dev.plist
recipients_app/ios/Runner/Info.plist

Updated dev flavor files for firebase integration. 
Current local emulators setup from our project is based on staging project and in the recipients_app we had some old demo / prod hybrid on our end.

chore(recipient_app): Update dev files for local emulators based on real staging project

---

recipients_app/lib/main.dart
recipients_app/lib/main_dev.dart
recipients_app/pubspec.lock
recipients_app/pubspec.yaml

Added appcheck. It's not yet enforced, so we are currently only monitoring verified and unverified requests.

feat(recipient_app): #234 - added appcheck to staging and prod

---

.github/workflows/execute-draw.yml

- set the count to 10
- updated to the latest version so we use an upcoming drand round and not the current one (as it's possible to know the current one!)

updated draw config for today's draw

---

website/src/app/[lang]/[region]/(website)/about-us/(sections)/team.tsx

- fixed a typo
- added subtle hover effect with tailwindcss

refactor(website): update teams page

---

recipients_app/lib/core/helpers/document_reference_converter.dart
recipients_app/lib/core/helpers/timestamp_converter.dart
recipients_app/lib/data/models/payment/social_income_payment.g.dart
recipients_app/lib/data/models/recipient.g.dart
recipients_app/lib/data/models/survey/survey.g.dart
recipients_app/pubspec.yaml

Trying to fix some issues around user profile fields. 
It seems to make it problematic, especially for new users who haven't got all the fields provided.

Fixing nullable fields and converters

---

website/src/app/[lang]/[region]/(website)/our-work/(assets)/milk.svg
website/src/app/[lang]/[region]/(website)/our-work/(sections)/contributors-orgs-carousel.tsx

feature(website): org carousel update with links (and added Milk)

---

shared/locales/de/website-home.json
shared/locales/de/website-our-work.json
shared/locales/en/website-home.json
shared/locales/en/website-our-work.json
ui/src/components/card.tsx
website/src/app/[lang]/[region]/(website)/(home)/section-5-card.tsx

Added missing German translations on the landing page

feature(website): missing translations DE

---

ui/src/components/accordion.tsx
website/src/app/[lang]/[region]/(website)/faq/faq-section.tsx

Small update of how we show FAQ questions

feature(website): faq design update

---

recipients_app/ios/Podfile.lock
recipients_app/lib/l10n/app_en.arb
recipients_app/lib/l10n/app_kri.arb
recipients_app/lib/view/pages/account_page.dart
recipients_app/pubspec.lock
recipients_app/pubspec.yaml

Add app version to a profile page
Resolving #683

feature(recipients_app): Add app version to profile page

---

admin/src/views/NextSurveysView.tsx

Added questionnaire type in NextSurveyView.tsx

feature(admin): adding questionnaire type to overview

---

website/src/app/api/stripe/checkout-session/create/route.ts

Preparational PR to have the option to append a campaignId to the stripe checkout

feature(website): campaign metadata in stripe checkout

---

website/src/components/footer/footer.tsx

Feature (Website): Updated twitter logo & name to X

---

website/src/app/context-providers.tsx

Required update for consent mode

feature(website): update consent mode

---

README.md

Adding Mux as a supporter (we received credits to use their service)

feature(general): readme update

---

shared/locales/en/website-faq.json

Fixed a typo in the campaign FAQ

feature(website): typo fixed

---

shared/locales/de/website-quiz.json
shared/locales/en/website-quiz.json
website/src/app/[lang]/[region]/(website)/(quiz)/right/page.tsx
website/src/app/[lang]/[region]/(website)/(quiz)/wrong/page.tsx

Adding two simple pages, which says right or wrong. They will be used in future newsletter for interactive quiz questions. The pages will be linked to the reveal the clicked answer is right or wrong.
It's only these two pages:
https://public-git-sandino-quiz-answers-social-income.vercel.app/en/ch/right
https://public-git-sandino-quiz-answers-social-income.vercel.app/en/ch/wrong

feature(website): quiz pages

---

recipients_app/pubspec.yaml

Last release app version in stores was 1.1.11+28

Increase app version and build number for the next app release

---

.github/workflows/execute-draw.yml

- updated the version of the action
- pass the PAT_TOKEN as a param so the PR creation has permissions

updated recipient draw action
