- .prettierrc
- .vscode/extensions.json
- ui/src/components/typography/Typography.stories.tsx
- ui/src/components/typography/Typography.tsx
- ui/src/foundations/Typography.stories.mdx
- ui/src/lib/util/documentation/components/TypographyItem.tsx
- ui/src/lib/util/documentation/components/TypographyList.tsx
- ui/src/lib/util/documentation/components/typography-list.css
- ui/src/main.css
- ui/tailwind.config.js
Add very basic typography documentation and a component for applying the stack.
Out of scope but planned: Applying variable font sizing (`clamp`) to the predefined typography stack.
**Note**: These sizes are not taken from the old website. We use the predefined sizing stack of Tailwind here, for the sake of standardization.
> [ui] Add typography foundations

- ui/src/components/combobox/Combobox.stories.tsx
- ui/src/components/combobox/Combobox.tsx
- ui/src/components/select/Select.stories.tsx
- ui/src/components/select/Select.tsx
_Cntributes to #84_
Comboboxes are the foundation of accessible autocompletes and command palettes, complete with robust support for keyboard navigation. Use the `SoCombobox` instead of the `SoSelect` whenever you have more than only a couple of options. The Combobox allows a more fine-grained search over all options compared to the select.
In the current combobox, the query field is inside the options' popover:
While technically feasible, the effort to make this usable in an accessible manner is currently too high. Therefore, querying is currently limited to typing directly into the field before it is opened.
> [ui] Add combobox component

- .github/workflows/admin.yml
- .github/workflows/functions.yml
- .github/workflows/ui.yml
- Makefile
- admin/package.json
- docker-compose.yaml
- package.json
Currently, we only trigger the checks when a file changes in the relevant module to not run them unnecessarily and slow down the merge process.
However, there is one problem with that. We can't make the checks required since they are not always triggered. This is also explained in https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks.
The github suggests a workaround by having another dummy workflow which always triggers, but that feels unnecessarily verbose.
A million commits later, I'm proposing to use this https://github.com/marketplace/actions/skip-duplicate-actions plugin which should address it as well.
I sneaked in another …
> feat(shared): make checks required - second attempt

- .github/workflows/admin.yml
- .github/workflows/functions.yml
- .github/workflows/ui.yml
To avoid skipping deployments like https://github.com/socialincome-san/public/actions/runs/3332682463/jobs/5513834686
```
Skip execution because the exact same files have been successfully checked in run https://github.com/socialincome-san/public/actions/runs/3332582140
```
> [shared] avoid skipping deployments

- admin/src/collections/Contributions.ts
- functions/src/etl/stripeWebhook.ts
- shared/types/admin/Contribution.ts
By default, firestore doesn't want to have undefined values.
Got the following error during the batch import of the production stripe charges:
```
Cannot use "undefined" as a Firestore value (found in field "monthly_interval"). If you want to ignore undefined values, enable `ignoreUndefinedProperties`.
```
> [functions] stripe firestore ingestion: avoid undefined

- functions/src/etl/stripeWebhook.ts
Ingesting the stripe charges into firestore sequentially times out after 540 secs which is the max runtime for a firebase v1 function. Latency from our firebase functions to firestore is surprisingly slow. Could be because the functions are running in the US, but our firestore is in Europe? At some point, we should run the functions in the same DC.
Switching to parallel ingestion.
> [functions] parallel stripe batch ingestion

- README.md
The sponsor link was linking to a broken GitHub sponsors page. This small PR fixes it :)
> Fix broken sponsor link.

- functions/package.json
- package-lock.json
Current deployment seems to fail due to missing dependencies. Somehow, the shared dependencies are not properly added in the functions. @mkue one more reason to get rid of the workspace setup since it's not properly supported by firebase.
> bugfix(functions): fix dependencies

- README.md
The URLs given for the issue labels in README were incorrect. This commit fixed them for better beginner exploration.
> Fix URLs for issues

- admin/src/views/NextSurveysView.tsx
- admin/src/views/PaymentsConfirmationView.tsx
Fixes #516. 
Previously, when the lists `upcoming survey` or `payments confirmations` collections were empty, the message "no row" was hidden. 
According to the documentation of the material UI's `DataGrid` component : 
> By default, the Data Grid has no intrinsic dimensions. Instead, it takes up the space given by its parent.
Source: [Data Grid Documentation](https://mui.com/x/react-data-grid/layout/)
One approach could be to set a minimum height for the parent of the `DataGrid`. 
The chosen approach is to make use of the autoHeight prop,  which enables `DataGrid` to adjust its size based on its content. 
Using this prop, we get the following result :
> Fixes empty state display bug with missing spaces

- recipients_app/lib/core/cubits/settings/settings_cubit.dart
- recipients_app/lib/data/models/payment/social_income_payment.g.dart
- recipients_app/lib/data/models/recipient.dart
- recipients_app/lib/data/models/recipient.g.dart
- recipients_app/lib/view/pages/account_page.dart
- recipients_app/pubspec.lock
- recipients_app/pubspec.yaml
Unified usage of preferred language field.
Right now both app and admin tool will use the same `main_language` property.
Also regenerated g files (it seems that we forgot about it on adding update date for payments 😮  )
> feat(recipients_app): Unify language property for user selected language, regenerated g files

- recipients_app/lib/data/repositories/user_repository.dart
- recipients_app/lib/l10n/app_en.arb
- recipients_app/lib/l10n/app_kri.arb
- recipients_app/lib/view/pages/payments_page.dart
> chore(recipients-app): Fix grey empty payments

- README.md
Added information for error handling for better guidance.
> refactor(general): update readme

- shared/locales/en/website-common.json
- website/src/components/logos/si-icon.tsx
- website/src/components/navbar/navbar-client.tsx
Refined NavBar: Adjusted Logo Sizes and Optimized Whitespace & Text for Mobile/Web Views
Out of scope was the CTA button "Take Action".
**Comparison**
Left: old / Right: new
> feature(website): refined navbar

- recipients_app/lib/data/models/payment/social_income_payment.dart
- recipients_app/lib/data/models/payment/social_income_payment.g.dart
- recipients_app/lib/data/models/recipient.dart
- recipients_app/lib/data/models/recipient.g.dart
- recipients_app/lib/data/repositories/payment_repository.dart
It was observed in #638 that recipients app is overriding some important data in firestore during confirming the payments. 
We had `set` method used but `update` should work better for this case. 
Also the `id` which is used by the app internally is not part of the shared contract so we will remove it with excluding it from generated `toJson` method.
> bug(recipients_app): fix payments updates from app to not override fields not used by the app

- ui/src/globals.css
- ui/tailwind.config.ts
Implement Unica77 font with custom font feature settings on website
> refactor(website): font configurations

- admin/src/collections/recipients/RecipientsProperties.ts
Changed the number validation so that every country code is allowed, but only numbers with a min. length of 5 and a max length of 15 digits. Moreover, now only integers are allowed because a phone number can't be a decimal number.
Note: I couldn't find any tests for the validation. Should we add some tests? 
It's my first open-source contribution, so I am happy about every feedback. 
Greetings Micha :)
> refactor(admin): update phone number validation

- functions/src/webhooks/admin/scripts/index.ts
- shared/src/stripe/StripeEventHandler.test.ts
- shared/src/stripe/StripeEventHandler.ts
The checkout metadata (e.g. campaignId) is attached to the checkout session, but not the charges or balanceTransaction. 
We need to make another API call to stripe to retrieve this for a charge.
Added a test.
> feature(shared): use checkout metadata in stripe hook

- README.md
Added inputs from @renestalder in [#707](https://github.com/socialincome-san/public/issues/707)
> feature(all): readme adaptions  

- shared/locales/de/website-donate.json
- shared/locales/en/website-donate.json
- website/src/app/[lang]/[region]/(website)/(home)/(sections)/active-campaign.tsx
- website/src/app/[lang]/[region]/(website)/(home)/(sections)/hero.tsx
- website/src/app/[lang]/[region]/(website)/(home)/page.tsx
- website/src/components/newsletter-popup/newsletter-popup-client.tsx
- website/src/components/tracking/cookie-consent-banner.tsx
Issue: We’ve received feedback that potential donors struggle to return to the campaign page, potentially reducing donations. I've addressed this issue promptly.
Solution: introducing a prominently displayed badge on the landing page. For our current campaign—the only one running at present—I hardcoded the URL and name directly into the badge.
Future: Looking ahead, we may automate this process by selecting which campaign to highlight directly from our backend, depending on the active campaign. Also we could display the progress of a campaign. However, this would require further design work and development, and for now, the hardcoded badge serves its purpose.
Note: The badge will be removed once the [campaign](https://socialincome.org/en/ch/campaign/MZmXEVHlDjOOFOMk82jW) ends. …
> feature(website): badge for highlighting active campaign on landing page

- CODEOWNERS
As discussed in #791 with @renestalder: he requested to be replaced as code owner. I added instead the three regular code owners until further notice. Additionally, I have added our private GitHub dev account (account used for this PR) as a code owner for the website and shared folder, enabling quicker fixes, such as typos and similar issues.
> feature(general): update codeowners

- recipients_app/android/app/build.gradle
This fixes the CodeMagic build error
```
Where:
Build file '/Users/builder/clone/recipients_app/android/app/build.gradle' line: 6
What went wrong:
Plugin [id: 'com.google.firebase.crashlytics'] was not found in any of the following sources:
```
> Remove gradle plugin "com.google.firebase.crashlytics" to fix the Android build

- shared/locales/en/website-survey.json
- website/src/app/[lang]/[region]/(website)/survey/checkin/page.tsx
- website/src/app/[lang]/[region]/(website)/survey/followup/page.tsx
- website/src/app/[lang]/[region]/(website)/survey/offboarding/page.tsx
- website/src/app/[lang]/[region]/(website)/survey/onboarding/page.tsx
This PR addresses the issue where the mobile app couldn't display any surveys because they were only accessible to recipients. The solution implemented recreates the four surveys and includes a generic link that can be used in demo mode of the mobile app.
Important: The surveys do not need to be functional and are only viewed through the web view of the mobile app. They are intended to provide the look and feel of a survey and display the actual questions used in the recipient surveys. I intentionally used the most basic elements, such as `<input>` and `<select>`, to build the survey page. I did not include follow-up questions or ranking, and the save button is intentionally disabled.
@MDikkii : the links to include in the demo mode are: 
1. Onboarding: .../survey/onboarding
2. Checkin: …
> feature(website): dummy surveys for mobile app in demo mode

- shared/src/stripe/StripeEventHandler.ts
- shared/src/types/user.ts
The webhook importing twint charges throws an error:
```
Error Could not create user for Stripe customer: cus_QLt13VT23sUUFy, unknown id, email or name Error: Could not create user for Stripe customer: cus_QLt13VT23sUUFy, unknown id, email or name at StripeEventHandler.constructUser (/workspace/dist/shared/src/stripe/StripeEventHandler.js:157:23) at StripeEventHandler.getOrCreateFirestoreUser (/workspace/dist/shared/src/stripe/StripeEventHandler.js:54:43) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async StripeEventHandler.storeCharge (/workspace/dist/shared/src/stripe/StripeEventHandler.js:176:29) at async StripeEventHandler.handleChargeEvent (/workspace/dist/shared/src/stripe/StripeEventHandler.js:28:24) at async …
```
> feature(functions): support twint

- shared/src/types/user.ts
To fix:
`Error: Value for argument "data" is not a valid Firestore document. Cannot use "undefined" as a Firestore value (found in field "personal.name"). If you want to ignore undefined values,`
> feature(functions): support twint (bugfix)

- shared/src/types/country.ts
- shared/src/utils/stats/ContributionStatsCalculator.ts
- ui/src/lib/utils.ts
- website/src/app/[lang]/[region]/(website)/transparency/finances/[currency]/section-3-cards.tsx
- website/src/app/[lang]/[region]/(website)/transparency/finances/[currency]/section-3.tsx
- website/src/app/[lang]/[region]/index.ts
- website/src/components/navbar/navbar-client.tsx
- website/src/components/providers/context-providers.tsx
- website/src/middleware.ts
Hey @dnhn! Looking at your #986 MR again, I realized that we can already set the country code of the request location as a cookie in the middleware. Doing it like this, it's not necessary anymore to do an extra request to the API endpoint you created because you can directly access the info in the cookie.
What do you think about this approach?
Seems to work as well:
> Set cookie with location of request country

- website/src/app/[lang]/[region]/(website)/journal/[slug]/page.tsx
- website/src/app/[lang]/[region]/(website)/journal/author/[slug]/page.tsx
- website/src/app/[lang]/[region]/(website)/journal/page.tsx
- website/src/app/[lang]/[region]/(website)/journal/tag/[slug]/page.tsx
- website/src/app/layout.tsx
- website/src/storyblok-init.ts
Sometimes the Storyblok api crashes. The bug can be reproduced at the UI, by navigating between Storyblok components on our pages. e.g clicking on a tag or the author of an article.
The bug is described on the following issues:
https://github.com/storyblok/storyblok-react/issues/952
https://github.com/vercel/next.js/issues/68882
> workaround for Storyblok initialization
